### PR TITLE
Vhf fixes

### PR DESCRIPTION
**Pull request by jketterl**
Allow switching between VHF and HF. Most important change is probably the introduction of tuner_clock, which is used in `SI5351A` calls, while tuner_frequency is used in `R820T2TUNE`. Also contained is the switching of the multiplexer for VHF/HF and some other, minor fixes.

### CODE REVIEW

**Comment by fventuri** [comment]
Thanks Jakob; I also was working on the R820T2TUNE frequency argument too.

I also noticed they added another possible USB control command: AD8340FX3, so I added that too (you may want to pull this change).

As per the USB control command 'R820T2STDBY', it looks like they have it defined as a write command, i.e. a command that sends a byte from the PC to the SDR, however looking at the source code in the ExtIO_sddc dll, they seem to use it as a way to return a status code from the SDR/FX3 back to the PC, so I am not really sure what to make of it (for now I just have it send a 0 to the FX3, but I'll have to ask them to understand better).

Franco

**Comment by fventuri** [comment]
BTW, are you able to receive in the VHF/UHF bands now?

**Comment by jketterl** [comment]
Yes, I am. Took me some time to figure it all out, but it's mostly working now. I'll send a more detailed update to the mailing list tomorrow, I'm off to bed for today ;)

**Comment by jketterl** [comment]
On the `R820T2STDBY`: I'm not really sure what the intention is there. Right now, there's nothing written to it, so it should be perfectly fine with the dummy byte. We can always change that at a later point.

You may have seen that the same applies to `R820T2INIT`, but this one takes 4 bytes instead. I kept the dummy data for that inline because `usb_device_control` is not prepared for that case, but we could of course make another `case` statement for it. The data that is sent is ignored in the firmware, and you get a `1` in the first byte of the response. I didn't evaluate that byte since it isn't tied to any conditions in the firmware (so if it is supposed to express "success", it will always be a successful call). Once again, this is just the state of the code right now.

**Pull request merged**
